services:
  app:
    build: .
    container_name: springboot_app
    ports:
      - "18000:18000"
    environment:
      MYSQL_HOST: mysql_db
      MYSQL_USER: root
      MYSQL_PASSWORD: 123
      MYSQL_PORT: 3306

    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: mysql_db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 123
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: